### ISSUE TITLE
Error meemaw.wasm try to connect websocket 

### ISSUE THREAD

**Issue by dome** [getmeemaw/meemaw#12]
meemaw.wasm try to connect websocket 

error dialing websocket: failed to WebSocket dial "ws://localhost:8421/accept?token=7b149f14-6f4e-4c3c-a5a6-3e1768ef7f04": WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""

**Comment by marceaul** [comment]
Hello @dome,

Thanks for your message!

You will need to provide more context, including what you have tried, if we are to identify issues.

Cheers

**Comment by dome** [comment]
I run the example . after create user and try to Accept Device i got error 
![Screenshot 2567-08-11 at 20 23 23](https://github.com/user-attachments/assets/f6f9ee3d-4d30-43f9-839d-67669f80e833)

**Comment by dome** [comment]
sorry
 if other device connecting it's work fine.

**Comment by marceaul** [comment]
Indeed, AcceptDevice is part of the multi-device process. You can find explanations here: https://getmeemaw.com/docs/multi-device

Logs are not great yet, glad you figured it out.
