### ISSUE TITLE
Server (and presumably Cloudflare) can see all the exported secret keys

### ISSUE THREAD

**Issue by CedarMist** [getmeemaw/meemaw#14]
https://github.com/getmeemaw/meemaw/blob/c9420a3e73d4e22a1c2788e75a9a952e77378ca8/server/tss_recover.go#L88

The server should provide its share (after authorization) to the user, so the user can recover their keys in private.

As it stands now, the server observes the secret key when it's recovered/exported. Presumably Cloudflare will also see this secret because they do SSL MITM on your hosted service.

Pls fix.

**Comment by marceaul** [comment]
Hey @CedarMist, thanks a lot for taking the time to go through the code! This is much appreciated.

Exporting the private key is kind of "defeating" the point of MPC anyway, but you're completely right that performing the operation on the client side will at least reduce the attack surface. I will update that.

PS: I'm curious about your use case and how you ended up here, any chance we can have a small chat? :) you can drop me an email here: hi@getmeemaw.com

**Comment by marceaul** [comment]
Closing this issue, changes have been merged. Also added an option in config to totally disable exports and multi-device, to allow for tighter control if required.

**Comment by CedarMist** [comment]
Nice, thanks for the quick turnaround
